eureka:
  client:
    register-with-eureka: true
server:
  port: 8050
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: apartment-rental-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
